name: Test Docs

on:
  pull_request:

jobs:
  test-docs:
    name: Test docs build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build
